namespace WinkNaturals.Models.Shopping
{
    public class SetListItemRequest
    {
        public decimal price { get; set; }
        public bool allowOnAutoOrder { get; set; }
        public string bundle { get; set; }
        public string businessVolumeEachOverride { get; set; }
        public string bv { get; set; }
        public int categoryID { get; set; }
        public string commissionableVolumeEachOverride { get; set; }
        public string currencyCode { get; set; }
        public decimal cv { get; set; }
        public int discount { get; set; }
        public int discountdynamicKitCategories { get; set; }
        public int? dynamicKitCategory { get; set; }
        public string field1 { get; set; }
        public string field2 { get; set; }
        public string field3 { get; set; }
        public string field4 { get; set; }
        public string field5 { get; set; }
        public string field6 { get; set; }
        public string field7 { get; set; }
        public string field8 { get; set; }
        public string field9 { get; set; }
        public string field10 { get; set; }
        public string groupMasterItemCode { get; set; }
        public string groupMasterItemDescription { get; set; }
        public string groupMembersDescription { get; set; }
        public string id { get; set; }
        public string image_01 { get; set; }
        public string image_02 { get; set; }
        public string image_03 { get; set; }
        public int inventoryFlag { get; set; }
        public string inventoryFlagDesc { get; set; }
        public bool? isDisabled { get; set; }
        public bool isDynamicKitMaster { get; set; }
        public bool isGroupMaster { get; set; }
        public bool isVirtual { get; set; }
        public string itemCode { get; set; }
        public string itemDescription { get; set; }
        public string itemID { get; set; }
        public string itemInventory { get; set; }
        public string itemTypeID { get; set; }
        public string largeImageUrl { get; set; }
        public string longDetail1 { get; set; }
        public string longDetail2 { get; set; }
        public string longDetail3 { get; set; }
        public string longDetail4 { get; set; }
        public bool OtherCheck1 { get; set; }
        public bool OtherCheck2 { get; set; }
        public bool OtherCheck3 { get; set; }
        public bool OtherCheck4 { get; set; }
        public bool OtherCheck5 { get; set; }
        public decimal OtherPrice1 { get; set; }
        public decimal OtherPrice2 { get; set; }
        public decimal OtherPrice3 { get; set; }
        public decimal OtherPrice4 { get; set; }
        public decimal OtherPrice5 { get; set; }
        public decimal OtherPrice6 { get; set; }
        public decimal OtherPrice7 { get; set; }
        public decimal OtherPrice8 { get; set; }
        public decimal OtherPrice9 { get; set; }
        public decimal OtherPrice10 { get; set; }
        public string ParentItemCode { get; set; }
        public string priceEachOverride { get; set; }
        public string priceTypeID { get; set; }
        public string productImage { get; set; }
        public decimal Quantity { get; set; }
        public string quantityModel { get; set; }
        public string selectDelivery { get; set; }
        public decimal shippingPriceEachOverride { get; set; }
        public string shortDetail1 { get; set; }
        public string shortDetail2 { get; set; }
        public string shortDetail3 { get; set; }
        public string shortDetail4 { get; set; }
        public string smallImageUrl { get; set; }
        public string sortOrder { get; set; }
        public string staticKitChildren { get; set; }
        public string subscriptionModel { get; set; }
        public string taxableEachOverride { get; set; }
        public string tinyImageUrl { get; set; }
        public string totalItems { get; set; }
        public string type { get; set; }
        public int weight { get; set; }
        public ShoppingCartItemType OrderType { get; set; }

    }
}

